/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rivetlogic.skype.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the SkypeGroup service. Represents a row in the &quot;rivetlogic_skype_SkypeGroup&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rivetlogic.skype.model.impl.SkypeGroupModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rivetlogic.skype.model.impl.SkypeGroupImpl}.
 * </p>
 *
 * @author Rivet Logic
 * @see SkypeGroup
 * @see com.rivetlogic.skype.model.impl.SkypeGroupImpl
 * @see com.rivetlogic.skype.model.impl.SkypeGroupModelImpl
 * @generated
 */
public interface SkypeGroupModel extends BaseModel<SkypeGroup> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a skype group model instance should use the {@link SkypeGroup} interface instead.
	 */

	/**
	 * Returns the primary key of this skype group.
	 *
	 * @return the primary key of this skype group
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this skype group.
	 *
	 * @param primaryKey the primary key of this skype group
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the skype group ID of this skype group.
	 *
	 * @return the skype group ID of this skype group
	 */
	public long getSkypeGroupId();

	/**
	 * Sets the skype group ID of this skype group.
	 *
	 * @param skypeGroupId the skype group ID of this skype group
	 */
	public void setSkypeGroupId(long skypeGroupId);

	/**
	 * Returns the user ID of this skype group.
	 *
	 * @return the user ID of this skype group
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this skype group.
	 *
	 * @param userId the user ID of this skype group
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this skype group.
	 *
	 * @return the user uuid of this skype group
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this skype group.
	 *
	 * @param userUuid the user uuid of this skype group
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this skype group.
	 *
	 * @return the user name of this skype group
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this skype group.
	 *
	 * @param userName the user name of this skype group
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this skype group.
	 *
	 * @return the create date of this skype group
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this skype group.
	 *
	 * @param createDate the create date of this skype group
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this skype group.
	 *
	 * @return the modified date of this skype group
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this skype group.
	 *
	 * @param modifiedDate the modified date of this skype group
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the group name of this skype group.
	 *
	 * @return the group name of this skype group
	 */
	@AutoEscape
	public String getGroupName();

	/**
	 * Sets the group name of this skype group.
	 *
	 * @param groupName the group name of this skype group
	 */
	public void setGroupName(String groupName);

	/**
	 * Returns the skype contacts of this skype group.
	 *
	 * @return the skype contacts of this skype group
	 */
	@AutoEscape
	public String getSkypeContacts();

	/**
	 * Sets the skype contacts of this skype group.
	 *
	 * @param skypeContacts the skype contacts of this skype group
	 */
	public void setSkypeContacts(String skypeContacts);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(SkypeGroup skypeGroup);

	@Override
	public int hashCode();

	@Override
	public CacheModel<SkypeGroup> toCacheModel();

	@Override
	public SkypeGroup toEscapedModel();

	@Override
	public SkypeGroup toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}